### ISSUE TITLE
댓글 삭제 인가 로직 이슈

### ISSUE THREAD

**Issue by BenchPress200** [100-hours-a-week/5-bluestarfish-blueberry-be#242]
## 댓글 삭제 시 인가 로직 오류

<img width="1028" alt="스크린샷 2024-09-18 오전 2 44 25" src="https://github.com/user-attachments/assets/b31ae691-757e-4638-946a-fd60a7431262">

댓글을 작성한 작성자가 삭제할 수 있는 것이 아닌 게시글 주인이 삭제할 수 있는 로직으로 보이고,
로컬과 배포환경에서 예기치 못한 401에러를 받았음

**Comment by DohunHyun** [comment]
확인했습니다. 수정하겠습니다

**Comment by DohunHyun** [comment]
https://github.com/100-hours-a-week/5-bluestarfish-blueberry-be/pull/243

수정하고 merge 했습니다.
