### ISSUE TITLE
회원 탈퇴 이후 다시 재가입 시 오류

### ISSUE THREAD

**Issue by DohunHyun** [100-hours-a-week/5-bluestarfish-blueberry-be#246]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 카카오 로그인한 계정 탈퇴 후 재 가입 시 오류 발생

**Comment by BenchPress200** [comment]
탈퇴 후 재가입하면 기존에 소프트딜리트했던 유저를 하드딜리트하고 다시 재생성하는 로직추가로 해결
